### ISSUE TITLE
Compatibility with safebrowser 

### ISSUE THREAD

**Issue by vicencarlos** [eLearning-BS23/moodle-quizaccess_proctoring#47]
There is a problem wiith safebrowser. The camera capture works, but there is a problem whit the  new window.

**Comment by vicencarlos** [comment]
Y just made a dirty change, in startAttemps.js and proctoring.js and if the test is made in the same window, you can use SafeBrowser and this plugin in order to capture video together, creating a very interesting complete solution to secure exams.

If you like y can create a patch with changes, with a new preference that choose answer the quiz in same o new window.

**Comment by shadman-ahmed-bs23** [comment]
Thanks for the suggestion. We have released a new version. We found the issues are occurring due to browser limitations with our screen capture feature. Unfortunately there is no standard in W3C for a certain property in screen sharing from browser. That is why it is not possible to support every browser's every version. That is why we decided to remove the screen capture feature in this latest version.
